name: Python CICD

on:
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest dvc_s3
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install DVC
      uses: iterative/setup-dvc@v1
    # - name: Configure AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@v2
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: us-east-2
    - name: Configure DVC
      run: |
        git config --global user.email "thichhocchui1999@gmail.com"
        git config --global user.name "dmtuan1409"
        git rm -r --cached data/*
        git commit -m "stop tracking data/*" 
    - name: Push data to S3 using dvc
      run: | 
        dvc pull
        dvc add data/*.csv
        dvc push -r myremote
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          api-key: ${{ secrets.RENDER_TOKEN }}
          service-id: srv-cieqellph6etu3u8suu0
